# Generated by Django 6.0.2 on 2026-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
