# Generated by Django 6.0.2 on 2026-03-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_booking_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.CharField(default='89.99', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='Pay After Service', max_length=50),
        ),
    ]
